use cargafacil;



CREATE TABLE USUARIO (
   ID integer(11) NOT NULL AUTO_INCREMENT,
   NOMEFAN varchar(45) NOT NULL,
   RSOCIAL varchar(45) NOT NULL,
   CIDADE  varchar(45) DEFAULT NULL,
   UF      varchar(2) DEFAULT NULL,
   SENHA   varchar(200) DEFAULT NULL,
   CONFSENHA varchar(200) DEFAULT NULL,
   CEL       varchar(45) DEFAULT NULL,
   TELEFONE  varchar(45) DEFAULT NULL,
   IE        varchar(45) DEFAULT NULL,
   CEP       varchar(45) DEFAULT NULL,
   CNPJ      varchar(35) DEFAULT NULL,
   EMAIL    varchar(100) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE CARGAS(
  IDCARGA INTEGER  NOT NULL AUTO_INCREMENT,
  SITCARGA VARCHAR (30) NOT NULL,
  DATACARREGAMENTO VARCHAR(30) NOT NULL,
  DATAAGENDAMENTO VARCHAR(30) NOT NULL,
  RESTRIHORA VARCHAR(30),
  TIPCARREGAMENTO VARCHAR(35) NOT NULL,
  QPRODUTOS INTEGER,
  RASTREAMENTO VARCHAR (3) NOT NULL,
  TIPFRETE VARCHAR (10) NOT NULL,
  TIPCARGA VARCHAR (40) NOT NULL,
  ESTIMAPRECO INTEGER NOT NULL,
  CIDCARRE VARCHAR (40) NOT NULL,
  CIDDESCAR VARCHAR(40) NOT NULL,
  DONOCARGA INTEGER NOT NULL,
  DATA_INSERT DATE NOT NULL,
  PRIMARY KEY (IDCARGA)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE CARGAS ADD CONSTRAINT FK_INSERT_USER FOREIGN KEY (DONOCARGA) REFERENCES USUARIO (ID);

DROP TABLE CARGAS;

show columns from cargas;

INSERT INTO CARGAS (SITCARGA,DATACARREGAMENTO,DATAAGENDAMENTO,RESTRIHORA,
                    TIPCARREGAMENTO,QPRODUTOS,ESTIMAPRECO,TIPCARGA,RASTREAMENTO,TIPFRETE,CIDCARRE,
                    CIDDESCAR,DONOCARGA,DATA_INSERT)
  VALUES('Aguardando Negociação','19/11-2015','19/11-2015','12:00','Paletizado',130020030,1030040,'Carga Viva','Sim','Fob','amparo','campinas', 7, CURRENT_DATE());

INSERT INTO CARGAS (SITCARGA,DATACARREGAMENTO,DATAAGENDAMENTO,RESTRIHORA,
                    TIPCARREGAMENTO,QPRODUTOS,ESTIMAPRECO,TIPCARGA,RASTREAMENTO,TIPFRETE,CIDCARRE,
                    CIDDESCAR,DONOCARGA,DATA_INSERT)
  VALUES('?','?','?','?','?',?,?,'?','?','?','?','?', ?, '?');




SELECT * FROM USUARIO;

SELECT * FROM cargas;
SELECT * FROM CARGAS;

delete from CARGAS where IDCARGA = 3;

truncate table cargas;

SELECT USU.NOMEFAN,
       USU.CEL,
       USU.TELEFONE,
       USU.EMAIL,
       USU.CNPJ,
       CG.IDCARGA,
       CG.SITCARGA,
       CG.QPRODUTOS,
       CG.TIPCARREGAMENTO,
       CG.TIPFRETE
FROM USUARIO USU,
     CARGAS  CG
WHERE CG.DONOCARGA = USU.ID;







